/**
 * Created by OXOYO on 2019/4/19.
 *
 *
 */

module.exports = {
  L00001: 'Login is successful! ',
  L00002: 'Login failed, generating token failed! ',
  L00003: 'Login failed! Please contact the administrator {0}({1})',
  L00004: 'Login failed, the parameters sent are incorrect! ',
  L00005: 'Get the user basic information successfully! ',
  L00006: 'Failed to get user basic information! ',
  L00007: 'Failed to get the basic information of the user, the sending parameters are incorrect! ',
  L00008: 'Authorization success! ',
  L00009: 'Authorization failed! Please contact the administrator {0}({1})',
  L00010: 'Authorization failed, the parameters sent are incorrect! ',
  L00011: 'The query resource list was successful! ',
  L00012: 'Query resource list failed! ',
  L00013: 'Adding resources successfully! ',
  L00014: 'Adding a resource failed, the resource already exists! ',
  L00015: 'Adding resources failed! ',
  L00016: 'Failed to add resources, the parameters sent are incorrect! ',
  L00017: 'Delete the resource successfully! ',
  L00018: 'Deleting resources failed! ',
  L00019: 'Deleting the resource failed, the sending parameters are incorrect! ',
  L00020: 'Editing resources is successful! ',
  L00021: 'Editing resources failed! ',
  L00022: 'Editing resources failed, the parameters sent are incorrect! ',
  L00023: 'Sort resources are successful! ',
  L00024: 'Sorting resources failed! ',
  L00025: 'The sorting resource failed, the sending parameters are incorrect! ',
  L00026: 'The query role list was successful! ',
  L00027: 'Failed to query the role list! ',
  L00028: 'Add a role successfully! ',
  L00029: 'Adding a role failed, the role already exists! ',
  L00030: 'Adding a role failed! ',
  L00031: 'Adding a role failed, the sending parameters are incorrect! ',
  L00032: 'Delete the role successfully! ',
  L00033: 'Deleting the role failed! ',
  L00034: 'Deleting the role failed, the sending parameters are incorrect! ',
  L00035: 'Edit the character successfully! ',
  L00036: 'Editing the role failed! ',
  L00037: 'Editing the role failed, the sending parameters are incorrect! ',
  L00038: 'Failed to read the log file, the log file does not exist! ',
  L00039: 'Read log file successfully! ',
  L00040: 'Failed to read the log file, log file parsing error! ',
  L00041: 'Query account list is successful! ',
  L00042: 'Failed to query the account list! ',
  L00043: 'Add account successfully! ',
  L00044: 'Failed to add account, the account already exists! ',
  L00045: 'Add account failed! ',
  L00046: 'Adding an account failed, the sending parameters are incorrect! ',
  L00047: 'Delete account successfully! ',
  L00048: 'Deleting an account failed! ',
  L00049: 'Deleting the account failed, the sending parameters are incorrect! ',
  L00050: 'Edit account successfully! ',
  L00051: 'Edit account failed! ',
  L00052: 'Edit account failed, the parameters sent incorrectly! ',
  L00053: 'Edit your profile successfully! ',
  L00054: 'Editing personal data failed! ',
  L00055: 'Editing profile failed, the account already exists! ',
  L00056: 'Editing profile failed, login status is abnormal! ',
  L00057: 'Editing the profile failed, the sending parameters are incorrect! ',
  L00058: 'Change password successfully! ',
  L00059: 'Change password failed! ',
  L00060: 'The password change failed, the old password is incorrect! ',
  L00061: 'The password change failed, the login status is abnormal! ',
  L00062: 'The password change failed. The parameters sent are incorrect! ',
  L00063: 'The password change failed. The confirmation password is inconsistent with the new password! ',
  L00064: 'The password change failed. The new password cannot be the same as the old password! ',
  L00065: 'The password change failed. The confirmation password is inconsistent with the new password! ',
  L00066: 'The password change failed. Please enter a numeric combination of 6 to 12 digits! ',
  L00067: 'The query task list was successful! ',
  L00068: 'Query task list failed! ',
  L00069: 'Add mission success! ',
  L00070: 'Add task failed! ',
  L00071: 'Adding a task failed, the sending parameters are incorrect! ',
  L00072: 'The editing task was successful! ',
  L00073: 'Editing task failed! ',
  L00074: 'The editing task failed, the sending parameters are incorrect! ',
  L00075: 'Delete the task successfully! ',
  L00076: 'Delete task failed! ',
  L00077: 'The deletion task failed, the sending parameters are incorrect! ',
  L00078: 'Query list is successful! ',
  L00079: 'Query list failed! ',
  L00080: 'Add classification successfully! ',
  L00081: 'Add category failed, this category already exists! ',
  L00082: 'Add classification failed! ',
  L00083: 'Edit classification is successful! ',
  L00084: 'Edit classification failed! ',
  L00085: 'Edit classification failed, the parameters sent incorrectly! ',
  L00086: 'Delete classification successfully! ',
  L00087: 'Deleting classification failed! ',
  L00088: 'Deleting the classification failed, the sending parameters are incorrect! '
}
